### ISSUE TITLE
npm start error on ubuntu [with &  w/o sudo]

### ISSUE THREAD

**Issue by carnotweat** [cozy/cozy-data-system#103]
Log: 
````
cozy-data-system@1.0.20 start: `node build/server.js`
npm ERR! `sh "-c" "node build/server.js"` failed with 1
npm ERR! Failed at the cozy-data-system@1.0.20 start script.
npm ERR! This is most likely a problem with the cozy-data-system package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/server.js
````
Details: build/server.js is just another regular Generated by CoffeeScript,changing host or port doesn't fix it.
PS: I am only beginning to browse here and It may be early to raise this issue,but this is different from [fixable] npm error thrown at ````sudo npm install cozy-monitor -g````,where is clearly says :````
No compatible version found: shelljs@'^0.3.0' ```` or ```` 'No compatible version found: path-extra@'^0.2.1' ````  with ````sudo npm install cozy-files -g```` .

**Comment by poupotte** [comment]
@jsilvestre , Can I close this issue ?
