### ISSUE TITLE
Binary cleaning

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-data-system#121]
I think I have more binaries than files, photos and attachments stored. We should thing about a way to clean unused binaries or fix what already exists.

**Comment by aenario** [comment]
Note about this : 

Some app might have to create the binary before creating the document (if they use unpausable stream, like mail or with replication and batch insert). Moreover, I am not sure how things go during binary update (is the new binary created before being linked).

A solution to this problem should take this into account.

**Comment by poupotte** [comment]
This issue should be fixed with #125 .
