### ISSUE TITLE
Handle thumbnail creation

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-data-system#122]
Thumbnails should be created when a new file is stored in the data system.

What is required:

* Generate a thumbnail on image file creation 
* Generate a new thumbnail on attachment modification
* Check for missing thumbnails and create it
* Handle error case and mark the file as not previewable

@poupotte @aenario @jsilvestre What do you think about it?
.

**Comment by aenario** [comment]
+1 all these. 

We need to  think hard about the size : is current "pick a photo from file" modal good from an UX point of view ?

Note : photo also makes 3 size of the photos (very small for albumview, ~ 1000px slideshow and row)  should this be kept in photo or handled by the DS (would need a "resize" API)

**Comment by jsilvestre** [comment]
I find it logical that the DS handles it, I like the idea of a platform service better (like a "service" but for applications to use), and basically the Data System is a platform service so this is all logical.

I agree with your points and Romain's points.

How would you see the thumbnails managed, database-wise? Do we create a separate file document for each or is it other binaries on the same files/photos? The latter makes more sense to me.

**Comment by frankrousseau** [comment]
@poupotte added it.
