### ISSUE TITLE
Warning email / Please click here with no link.

### ISSUE THREAD

**Issue by aenario** [cozy/cozy-data-system#134]
It is because my cozy_instance has a domain set to empty string.

https://github.com/cozy/cozy-data-system/blob/89645d6bb7e9215c37a66f834a08d936fba51a13/server/lib/encryption.coffee#L34-L35

**Comment by frankrousseau** [comment]
@aenario It looks fixed, could you try again?

**Comment by clochix** [comment]
@aenario Any news on this ? Could we close it ???
