### ISSUE TITLE
The latest version doesn't seem to like passwords

### ISSUE THREAD

**Issue by babolivier** [cozy/cozy-data-system#160]
Hi,

To keep it short, I have [this create call](https://github.com/babolivier/cozy-isen-ent/blob/e1f867f3d2d80054e24e842e2dd70da169e82ff6/server/models/login.coffee#L93-L101). The console.log sure isn't really secure, but I was working on an issue where I couldn't retrieve a supposed saved password, so I wanted to know what cozydb saved.
I have this output:

```
{ username: 'baboli18',
  password: '***********',
  tgc: 
   { key: 'CASTGC',
     value: 'TGT-598-rkm2FKaZBHIDLYFAORuWljLn1b2h26CVyW5ka6qlTeI3tfjeZj-cas',
     domain: 'web.isen-bretagne.fr',
     path: '/cas',
     secure: true,
     hostOnly: true,
     creation: '2015-08-24T16:29:18.975Z',
     lastAccessed: '2015-08-24T16:29:18.977Z' },
  jsessionid: 
   { key: 'JSESSIONID',
     value: 'F62053FD6C6FA9BAD8B96B6564919888',
     domain: 'web.isen-bretagne.fr',
     path: '/',
     secure: true,
     hostOnly: true,
     creation: '2015-08-24T16:29:17.800Z',
     lastAccessed: '2015-08-24T16:29:18.977Z' },
  _id: 'b359c1912482968bb7e0d84c76012f35',
  _attachments: undefined,
  _rev: undefined,
  id: 'b359c1912482968bb7e0d84c76012f35',
  docType: 'caslogin',
  binaries: undefined }
```

The censored "password" field is my password, which match with the valid value.

After this, I go look in the DataBrowser, the password field isn't filled. The next step in the app include a check with the said password, which seems to be undefined.
[Here](https://bren.cozycloud.cc/public/haste/GfcZzrEc)'s the log from my DataSystem.

I updated the data-system to version 2.0.7 today, and it seems that this latest version is causing the issue. I tried with another cozydb version and the issue still happen.

If it can help, I'm running the app on an ISEN Cozy.

**Comment by jsilvestre** [comment]
I did not manage to reproduce the bug (in this specific app and in another). Nobody complained about it in another app, so I guess it's something else. I'm closing, but will keep an eye on that matter.
