### ISSUE TITLE
TypeError: Cannot read property 'targetDocType' of null

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-data-system#206]
Some users have reported this error after migrating their database from one server to another.
See this threads [1](https://forum.cozy.io/t/resolu-probleme-pour-restaurer-cozy-couchdb-apres-reinstallation-de-los/1713) and [2](https://forum.cozy.io/t/resolu-probleme-pour-restaurer-cozy-couchdb-apres-reinstallation-de-los/1713)

**Comment by poupotte** [comment]
Thanks @clochix !
