### ISSUE TITLE
30G of cozy.couch - any chance of reducing it ? 

### ISSUE THREAD

**Issue by arthurlutz** [cozy/cozy-data-system#209]
A while back I installed a cozy in a docker, and am barely using it. I've imported some data (but not gigabytes) into it, and have two small konnectors configured. 

Looking at disk space usage, I find that cozy.couch has grown to 30G. That seems a lot for my usage. 

Are there tools to explore what's taking up space ? Maybe some logs ? Versioning ? 

On top of that it's in a docker, but volumes seem to be configured correctly.

**Comment by nono** [comment]
You can try these 2 commands:

```sh
cozy-monitor compact
cozy-monitor compact-all-views
```

See https://docs.cozy.io/en/host/manage.html#database-management for the explanation.

**Comment by clochix** [comment]
Hi @arthurlutz,

Unfortunately, this is a drawback of using CouchDB: each time a record is updated, the files storing the database grow, so you have to often compact them. You can use `cozy-monitor compact` to compact the database itself, `cozy-monitor view-list` to get the size of all views, `cozy-monitor compact-view xxx` to compact one of them (if you use Emails, you'll probably have to often use `cozy-monitor compact-view message`), and `cozy-monitor compact-all-views` to compact all views.

Compacting database is something only self-hosted users need, so we don't plan to add this option t o the main interface. @nledez is working on [an application](https://github.com/cozy/cozy-self-hosting/) for self hosted users. Allowing to compact the database from this application would make sense. You could also write a cron task on the server to compact and backup the database one in a while.

By connecting to localhost:5984, you'll access to Futon, a Web front end to CouchDB where you'll be able to explore the database.

**Comment by clochix** [comment]
Hi @arthurlutz,
Did you manage to compact your database?
I saw you opened an issue to add commands related to compaction to cozy-self-hosting. Can we close this issue or do you still have unanswered questions?

**Comment by arthurlutz** [comment]
@clochix sure, the issue is fixed eventough it points to other needs that should be described in other issues. Thanks for your help.
