### ISSUE TITLE
Allow replication to access /replication/_all_docs URLs

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-data-system#259]
Requested by @kosssi 

URL `POST /replication/_all_docs?include_docs=true` are not allowed by [checkPermissionsPostReplication](https://github.com/cozy/cozy-data-system/blob/master/server/middlewares/utils.coffee#L58).

@kosssi would like to allow them. We must be very cautious of the security implications

**Comment by nono** [comment]
[POST /{db}/_all_docs](http://docs.couchdb.org/en/1.6.1/api/database/bulk-api.html#post--db-_all_docs) is for getting multiple docs in one request. To allow it and be sure to respect the permissions, it's enough to check the doctype for each of the returned documents. There are no streaming issues or timeout like for other methods used in replication, so it shouldn't too complicated.
